version: '3.8'
services:
  spring-boot-app:
    build: ./letscode
    ports:
      - "8080:8080" 
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.9-management 
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest